export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const GET_ERRORS = 'GET_ERRORS';

export const GET_STORES = 'GET_STORES';
export const GET_MAP_STORES = 'GET_MAP_STORES';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_AVANTAGES = 'GET_AVANTAGES';
export const GET_RECOMMENDATIONS = 'GET_RECOMMENDATIONS';
export const GET_AVANTAGE = 'GET_AVANTAGE';
export const AVANTAGES_LOADING = 'AVANTAGES_LOADING';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const USER_LOADING = 'USER_LOADING';
export const CONFIRM_USER = 'CONFIRM_USER';
export const SUBSCRIBE_USER = 'SUBSCRIBE_USER';
export const GET_CODE = 'GET_CODE';

export const USE_COUPON = 'USE_COUPON';
export const GET_COUPONS = 'GET_COUPONS';
export const GET_MONTHS = 'GET_MONTHS';
export const CREATE_COUPON = 'CREATE_COUPON';
